### ISSUE TITLE
Build Error: The type or namespace name `ObservableCollection`1' could not be found.

### ISSUE THREAD

**Issue by msafder** [RobertKozak/MonoMobile.Views#11]
Hello,

I wanted to give this project a test drive so I did a fresh Pull from github. But when I try to build the solution I'm getting this build error on line 44 of the EnumCollection.cs file:

/Projects/MonoMobile.Views/Collections/EnumCollection.cs(35,35): Error CS0246: The type or namespace name `ObservableCollection`1' could not be found. Are you missing a using directive or an assembly reference? (CS0246) (MonoMobile.Views)

I checked and there is "using System.Collections.ObjectModel;". Any ideas?

thanks in advance,

-mo

**Comment by RobertKozak** [comment]
What version of the iOS and MonoTouch are you using? The ObservableCollection is in the System.dll and should be available.

**Comment by msafder** [comment]
I'm still using Monotouch v3.2.6.9797 and IOS 4. Does that make a difference?

**Comment by RobertKozak** [comment]
I think you need MonoTouch 4.X. Right now the Stable Release is MonoTouch 4.0.6, MonoTouch 4.1 is in Beta and MonoTouch 4.9 is in Alpha.

I would suggest you upgrade to MonoTouch 4.0.6

-----Original Message-----

**Comment by msafder** [comment]
Thanks Robert. I upgraded to MonoTouch  4.1.0 (beta) and it builds just fine now. Thanks for the quick response!
