### ISSUE TITLE
Bug when using Selection on ObservableCollection<T>

### ISSUE THREAD

**Issue by follesoe** [RobertKozak/MonoMobile.Views#8]
If you got an IEnumerable<T> that you are using as a Selection there should be an easy way to define what should be displayed on the Root-element. 

```
    [Caption("Color theme")]
    [Bind("SelectedTheme", "SelectedItem")]
    [Root(ViewType = typeof(UITableViewElementCell))]
    [Selection]
    [PopOnSelection]
            public ObservableCollection<Theme> Themes { get; private set; }             
```

The code above also doesn't pushed the selected Theme to the SelectedTheme property. The setter is called, but with the same value all the time, i.e. not the new selected value.

The PopOnSelection attribute does not work in this case either, as you must click "Back" to navigate back.

**Comment by RobertKozak** [comment]
This should be working now after last checkin. Let me know if you still have probs.
