### ISSUE TITLE
MultilineAttribute

### ISSUE THREAD

**Issue by TravisTheTechie** [RobertKozak/MonoMobile.Views#9]
The multiline attribute does not produce a usable text entry field. It's just a minimal line on, which no ability to get a cursor in it.

**Comment by TravisTheTechie** [comment]
Started down this road: https://github.com/legomaster/MonoMobile.MVVM/commit/65d0c45a184240af655a19040f161a5e931298da

Not sure how to enforce word wrap here, and I had to change the caption to "A" since I want the number of lines for entry and not caption. Might be better way than how I approached that.

**Comment by RobertKozak** [comment]
Fixed in latest
